image: debian

pipeline:
  stages:
  - name: first
    autorun: true
  - name: second
    autorun: true

jobs: 
  - stage: first
    name: echo foo
    deploy:
      - echo foo
  - stage: first
    name: echo foo2
    deploy:
      - echo foo
  - stage: first
    name: echo foo3
    deploy:
      - echo foo
      - sleep 100
  - stage: second
    name: echo bar
    deploy:
      - echo bar
