pipeline:
  stages:
  - name: first
    autorun: true

jobs: 
  - stage: first
    name: output producer
    deploy:
      - echo foo
      - sleep 3
      - echo bar
      - sleep 10
      - echo foobar
      - sleep 5
      - echo uuu
      - sleep 5
      - echo aaa
      - sleep 5
      - echo ooo
