pipeline:
  stages:
  - name: first
    autorun: false
  - name: second
    autorun: false

jobs: 
  - stage: first
    name: echo foo
    deploy:
      - echo foo
  - stage: second
    name: echo bar
    deploy:
      - echo bar
      
