pipeline:
  stages:
  - name: first
    autorun: true
  - name: second
    autorun: true
  - name: third
    autorun: false

jobs: 
  - stage: first
    name: echo foo
    deploy:
      - echo foo
  - stage: second
    name: echo bar
    deploy:
      - echo bar
  - stage: third
    name: echo foobar
    deploy:
      - echo foobar
