image: debian

pipeline:
  stages:
  - name: first
    autorun: true
  - name: second
    autorun: true

jobs: 
  - stage: first
    name: echo foo
    deploy:
      - sleep 1000
      - echo foo
  - stage: second
    name: echo bar
    deploy:
      - echo end
